/**
 * As 50 falas do Sábio — todas sobre a luz, faladas em sequência (tecla H).
 * A ordem tem arco: chegada (1–6) → ensinamentos, do simples ao vertiginoso
 * (7–38) → revelações veladas sobre este mundo: a princesa, o lobo, o sol
 * parado, o rosto-sol do viajante (39–46) → despedida (47–50). Depois da
 * 50ª o sábio parte em luz (ver Sage.tsx).
 */
export const SAGE_LINES: readonly string[] = [
  'Chegaste. Eu sabia que virias: quem espera no meio do nada não conta o tempo — acende-o.',
  'Guarda o teu nome. O escuro o sabe desde antes de ti; a luz ainda o aprende, letra por letra.',
  'Esperei eras neste vazio. A luz também é isto: ficar, quando tudo seria desculpa para ir.',
  'Os cães te anunciaram antes dos teus passos. Bicho nenhum segue homem; seguem calor. E tu ardes.',
  'Eu era jovem quando este orbe era um sol inteiro. Hoje ele não ilumina; testemunha.',
  'Vieste perguntar o que é a luz. Eu te pergunto: o que era o mundo antes de haver alguém para vê-la?',
  'A luz nada promete; por isso nunca mente.',
  'Toda sombra é uma confissão: algo ficou de pé diante da luz.',
  'A luz não entra onde é convidada; entra onde há fresta.',
  'A estrela não sabe que ilumina; por isso ilumina.',
  'O fogo pequeno teme o vento; o fogo verdadeiro casa com ele.',
  'Quem fecha a luz no punho fica apenas com o calor da própria mão.',
  'A aurora não vence a noite; convence-a.',
  'A luz que exige ser vista já começou a apagar-se.',
  'O gelo guarda a luz melhor que o fogo: ama sem consumir.',
  'Tudo o que arde diminui, exceto o que arde por outro.',
  'A escuridão não engole a luz; guarda-a na boca, sem saber engolir.',
  'Não poupes a tua luz: nunca vi chama apagar-se por arder demais, só por medo de arder.',
  'Nenhuma sombra tem peso, cheiro ou voz. E ainda assim tu foges dela: temes uma ausência.',
  'Semeia luz onde nunca verás a colheita; foi assim que o sol começou.',
  'Quem já foi escuridão ilumina sem vaidade.',
  'Há duas cegueiras: a de quem não vê a luz e a de quem não vê mais nada além dela.',
  'Não há caminho até a luz; há a luz fingindo ser caminho.',
  'Apagar-se também é ofício da luz; só o brilho falso não sabe descansar.',
  'Não se carrega a luz; anda-se dentro dela, como o peixe no mar.',
  'A luz não tem pressa: já chegou a todos os lugares aonde tu ainda vais.',
  'A noite não é tua inimiga: é a luz medindo a tua saudade dela.',
  'Um fóton não envelhece. Para a luz, nascer e tocar o teu olho são o mesmo instante.',
  'A luz não divide o mundo em dia e noite: divide-te em antes e depois de vê-la.',
  'Cada cor é uma pergunta que a luz faz; cada coisa responde devolvendo o que não pôde guardar.',
  'Vês o sol como ele era há oito minutos. Até o céu só sabe falar do passado.',
  'A luz não atravessa a pedra, mas atravessa o vazio inteiro. O nada é o seu caminho mais fiel.',
  'Toda estrela que vês pode já estar morta. A luz é a única coisa que sobrevive ao próprio mensageiro.',
  'O olho é um poço onde a luz cai para sempre. Ver é sepultar fótons — e chamar isso de mundo.',
  'Tu és cinza de estrelas que explodiram para que a luz tivesse onde pousar.',
  'O universo é quase todo escuridão. E ainda assim, tudo o que sabemos dele chegou pela luz.',
  'Para a luz, a tua vida dura menos que um piscar. E ainda assim ela atravessa eras para te encontrar.',
  'A luz cabe num grão e cobre o universo. Não perguntes o tamanho dela; pergunta o teu.',
  'Ela é pálida porque deu toda a sua luz a alguém. Não corras atrás do que já te pertence.',
  'O lobo não caça a tua carne; caça o instante em que esqueces de brilhar.',
  'O sol não parou por cansaço. Parou no dia em que alguém teve medo de perdê-lo. Ainda não sei se fui eu.',
  'Quando o escuro te alcança, o mundo não acaba: apenas pisca. E há coisas que vivem entre um piscar e outro.',
  'Guarda-te do que corre em quatro patas: as brasas nos seus olhos são o resto de um fogo que alguém tentou apagar.',
  'Ela te olhou uma única vez. Para alguns, isso basta para caminhar uma eternidade.',
  'Os cães dormem tranquilos ao teu lado: para eles, tu és o amanhecer que não os abandona.',
  'Ninguém carrega um sol no lugar do rosto por acaso. Alguém, um dia, apagou-se para que tu acendesses.',
  'Não perguntes por que a noite volta. Pergunta por que a luz sempre a perdoa.',
  'Um dia o teu capuz cairá, e o mundo verá o que sempre soube: nunca houve viajante, só caminho aceso.',
  'Quando tudo escurecer de vez, escuta: a luz não faz som — mas o passo dela faz.',
  'Vai. Ninguém segue a luz: ela recua na medida do teu amor, para que nunca pares de andar.',
]
